#ifndef GOMOKU_RULE_H
#define GOMOKU_RULE_H

#define BOARD_SIZE 15
#define ROLE_PLAYER 0
#define ROLE_GOMOKO 1

#define DIRECTION_HORIZONTAL 0
#define DIRECTION_VERTICAL 1
#define DIRECTION_DIAGONAL 2
#define DIRECTION_BACK_DIAGONAL 3

#endif //GOMOKU_RULE_H
